FROM mambaorg/micromamba:0.27.0

# This dockerfile uses cached mounts, so to build use e.g.
# $ DOCKER_BUILDKIT=1 docker build .

WORKDIR /tmp

ADD checkm2.yml /checkm2.yml
RUN --mount=type=cache,target=/opt/conda/pkgs micromamba install -c conda-forge -c bioconda -c defaults -n base git -f /checkm2.yml
RUN --mount=type=cache,target=/opt/conda/pkgs micromamba clean --all --yes
# This is needed to activate the environment in the dockerfile
ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN git clone https://github.com/chklovski/checkm2 && cd singlem && git checkout vCHECKM2_VERSION

# Download default data
RUN mkdir -p singlem/db && cd singlem/db && /tmp/singlem/bin/singlem data --output-directory .

######### UPDATE ME !!!!!!!!!! #########
ENV SINGLEM_METAPACKAGE_PATH=/tmp/singlem/db/S3.0.5.metapackage20220806.smpkg.zb
# Checks whether the metapackage is up to date
RUN /tmp/singlem/bin/singlem data --verify

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/_entrypoint.sh","/tmp/checkm2/bin/checkm2"]

# CMD /bin/bash
